central_url: "https://{{ central_addr }}:{{ central_port }}"

openshift_policy_fixes:
  - name: "Curl in Image"
    namespaces:
      - openshift-apiserver-operator
      - openshift-apiserver
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-operator-lifecycle-manager
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-ovn-kubernetes
  - name: "Docker CIS 4.1: Ensure That a User for the Container Has Been Created"
    namespaces:
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-monitoring
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-ovn-kubernetes
  - name: "Iptables Executed in Privileged Container"
    namespaces:
      - openshift-cluster-node-tuning-operator
      - openshift-sdn
      - openshift-ovn-kubernetes
  - name: "iptables Execution"
    namespaces:
      - openshift-cluster-node-tuning-operator
      - openshift-sdn
      - openshift-ovn-kubernetes
  - name: "Docker CIS 5.16: Ensure that the host's IPC namespace is not shared"
    namespaces:
      - openshift-cluster-node-tuning-operator
      - openshift-ovn-kubernetes
  - name: "Docker CIS 5.9 and 5.20: Ensure that the host's network namespace is not shared"
    namespaces:
      - openshift-cluster-node-tuning-operator
      - openshift-ovn-kubernetes
  - name: "Docker CIS 4.1: Ensure That a User for the Container Has Been Created"
    namespaces:
      - openshift-cluster-node-tuning-operator
      - openshift-ovn-kubernetes
  - name: "Docker CIS 5.15: Ensure that the host's process namespace is not shared"
    namespaces:
      - openshift-cluster-node-tuning-operator
      - openshift-machine-config-operator
      - openshift-monitoring
      - openshift-sdn
      - openshift-ovn-kubernetes
  - name: "Environment Variable Contains Secret"
    namespaces:
      - openshift-image-registry
  - name: "Privileged Containers with Important and Critical Fixable CVEs"
    namespaces:
      - openshift-apiserver
      - openshift-cluster-csi-drivers
      - openshift-cluster-node-tuning-operator
      - openshift-dns
      - openshift-etcd
      - openshift-image-registry
      - openshift-kube-apiserver
      - openshift-machine-config-operator
      - openshift-multus
      - openshift-oauth-apiserver
      - openshift-sdn
      - openshift-ovn-kubernetes
  - name: "Fixable Severity at least Important"
    namespaces:
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-operator-lifecycle-manager
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-ovn-kubernetes
  - name: "Mounting Sensitive Host Directories"
    namespaces:
      - openshift-apiserver
      - openshift-cluster-csi-drivers
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-version
      - openshift-dns
      - openshift-etcd
      - openshift-image-registry
      - openshift-kube-apiserver
      - openshift-kube-controller-manager
      - openshift-kube-scheduler
      - openshift-machine-config-operator
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-sdn
      - openshift-ovn-kubernetes
  - name: "No resource requests or limits specified"
    namespaces:
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-operator-lifecycle-manager
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-ovn-kubernetes
  - name: "Privileged Container"
    namespaces:
      - openshift-apiserver
      - openshift-cluster-csi-drivers
      - openshift-cluster-node-tuning-operator
      - openshift-dns
      - openshift-etcd
      - openshift-image-registry
      - openshift-kube-apiserver
      - openshift-machine-config-operator
      - openshift-multus
      - openshift-oauth-apiserver
      - openshift-ovn-kubernetes
  - name: "Process with UID 0"
    namespaces:
      - openshift-dns
      - openshift-etcd
      - openshift-image-registry
      - openshift-multus
      - openshift-sdn
      - openshift-ovn-kubernetes
  - name: "Red Hat Package Manager in Image"
    namespaces:
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-operator-lifecycle-manager
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-ovn-kubernetes
  - name: "Wget in Image"
    namespaces:
      - openshift-apiserver
      - openshift-apiserver-operator
      - openshift-authentication
      - openshift-authentication-operator
      - openshift-cloud-credential-operator
      - openshift-cluster-csi-drivers
      - openshift-cluster-machine-approver
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-storage-operator
      - openshift-cluster-version
      - openshift-config-operator
      - openshift-console
      - openshift-console-operator
      - openshift-controller-manager
      - openshift-controller-manager-operator
      - openshift-dns
      - openshift-dns-operator
      - openshift-etcd
      - openshift-etcd-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-ingress-operator
      - openshift-insights
      - openshift-kube-apiserver
      - openshift-kube-apiserver-operator
      - openshift-kube-controller-manager
      - openshift-kube-controller-manager-operator
      - openshift-kube-scheduler
      - openshift-kube-scheduler-operator
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-machine-api
      - openshift-machine-config-operator
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-operator
      - openshift-oauth-apiserver
      - openshift-operator-lifecycle-manager
      - openshift-sdn
      - openshift-service-ca
      - openshift-service-ca-operator
      - openshift-ovn-kubernetes
