---
- name: Get deployments
  uri:
    url: "{{ central_url }}/v1/deployments?query=Deployment:\"{{ item }}\""
    method: GET
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: true
    validate_certs: no  
  register: deployments
  loop:
    - visa-processor
    - backend-atlas
    - asset-cache

- name: Set deployment id
  set_fact: 
    deployment_ids: "{{ deployments | json_query('results[*].json.deployments[].id') }}"

- name: Get deployment details
  uri:
    url: "{{ central_url }}/v1/deployments/{{ item }}"
    method: GET
    user: admin
    password: "{{ admin_password }}"
    force_basic_auth: true
    validate_certs: no  
  register: deployment_details
  loop: "{{ deployment_ids }}"

- name: Update baselines
  uri:
    url: "{{ central_url }}/v1/processbaselines"
    body: "{{ lookup('template', 'templates/baseline/baseline.json.j2' ) }}"
    method: PUT
    user: admin
    password: "{{ admin_password }}"
    body_format: json
    force_basic_auth: true
    validate_certs: no
  loop: "{{ deployment_details.results }}" 
  loop_control:
    label: "{{ item.json.name }}"

- name: Lock baselines
  uri:
    url: "{{ central_url }}/v1/processbaselines/lock"
    body: "{{ lookup('template', 'templates/baseline/lock.json.j2' ) }}"
    method: PUT
    user: admin
    password: "{{ admin_password }}"
    body_format: json
    force_basic_auth: true
    validate_certs: no
  loop: "{{ deployment_details.results }}" 
  loop_control:
    label: "{{ item.json.name }}"