- name: Get deployments
  uri:
    url: "{{ central_url }}/v1/deployments?query=Deployment:\"{{ item }}\""
    method: GET
    headers:
     Authorization: "Bearer {{ rox_api_token }}"
    validate_certs: no  
  register: deployments
  loop:
    - visa-processor
    - patient-db

- name: Set deployment id
  set_fact: 
    deployment_ids: "{{ deployments | json_query('results[*].json.deployments[].id') }}"

- name: Get deployment details
  uri:
    url: "{{ central_url }}/v1/deployments/{{ item }}"
    method: GET
    headers:
     Authorization: "Bearer {{ rox_api_token }}"
    validate_certs: no  
  register: deployment_details
  loop: "{{ deployment_ids }}"

- name: Get jump-host id
  uri:
    url: "{{ central_url }}/v1/deployments?query=Deployment:\"jump-host\""
    method: GET
    headers:
     Authorization: "Bearer {{ rox_api_token }}"
    validate_certs: no  
  register: jumphost

- debug: var=jumphost

- name: Establish baselines
  uri:
    url: "{{ central_url }}/v1/networkbaseline/{{ jumphost.json.deployments[0].id }}"
    method: GET
    headers:
     Authorization: "Bearer {{ rox_api_token }}"
    validate_certs: no
  loop: "{{ deployment_details.results }}" 
  loop_control:
    label: "{{ item.json.name }}"

- name: Update baselines
  uri:
    url: "{{ central_url }}/v1/networkbaseline/{{ jumphost.json.deployments[0].id }}/peers"
    body: "{{ lookup('template', 'templates/network_anomalies/peers.json.j2' ) }}"
    method: PATCH
    headers:
     Authorization: "Bearer {{ rox_api_token }}"
    body_format: json
    validate_certs: no
  loop: "{{ deployment_details.results }}" 
  loop_control:
    label: "{{ item.json.name }}"
