---
- hosts: localhost

  pre_tasks:
    - copy:
        dest: "files/kubeconfig"
        content: "{{ lookup('env', 'KUBECONFIG_BASE64') | b64decode }}"
    - set_fact:
        central_port: "{{ lookup('env', 'CENTRAL_PORT') | default('443', True) }}"
        central_addr: "{{ lookup('env', 'CENTRAL_ADDR') }}"
        rox_api_token: "{{ lookup('env', 'ROX_API_TOKEN') }}"
        orchestrator: "{{ lookup('env', 'ORCHESTRATOR') | default('openshift', True) }}"
        kubeconfig: "files/kubeconfig"
    - name: Installing on k8s
      set_fact:
        orchestrator_tool: kubectl
      when:
        orchestrator == "k8s"
    - name: Installing on OpenShift
      set_fact:
        orchestrator_tool: oc
      when:
        orchestrator == "openshift"

  tasks:
    - import_role:
        name: demo
    - import_role:
        name: pipelines
      when:
        orchestrator == "openshift"
