apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: rox-generate-netpol
  namespace: pipeline-demo
spec:
  params:
    - name: rox_central_endpoint
      type: string
      description: Secret containing the address:port tuple for StackRox Central (example - rox.stackrox.io:443)
    - name: rox_api_token
      type: string
      description: Secret containing the StackRox API token with CI permissions
    - name: file
      type: string
      description: YAML file in the deployfiles workspace
  results:
      - name: check_output
        description: Output of `roxctl generate netpol`
  workspaces:
    - name: deployfiles
      description: |
        The folder containing deployment files
      mountPath: /deployfile
  steps:
    - name: rox-generate-netpol
      image: centos
      env:
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.rox_api_token)
              key: rox_api_token
        - name: ROX_CENTRAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: $(params.rox_central_endpoint)
              key: rox_central_endpoint
      script: |
        #!/usr/bin/env bash
        set +x
        cat /deployfile/deploy.yml
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl  > /dev/null; echo "Getting roxctl"
        chmod +x ./roxctl  > /dev/null
        ./roxctl generate netpol /deployfile/$(params.file) 
