---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-yaml-file
  namespace: pipeline-demo
spec:
  params:
    - name: yaml
      type: string
      description: Contents of the deployment YAML to be checked
  workspaces:
    - name: deployfiles
      description: |
        The folder containing deployment files
      mountPath: /deployfile
  steps:
    - name: write-yaml
      image: centos
      script: |
        #!/usr/bin/env bash
        echo "$(params.yaml)" | base64 -d > /deployfile/deploy.yml

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rox-deploy-pipeline
  namespace: pipeline-demo
spec:
  description: Rox demo deployment check
  params:
    - name: yaml
      type: string
      description: Contents of the deployment YAML to be checked
  workspaces:
    - name: files  
  tasks:
  - name: write-yaml
    taskRef:
      name: write-yaml-file
    workspaces:
      - name: deployfiles
        workspace: files
    params:
    - name: yaml
      value: $(params.yaml)
  - name: deploy-check
    runAfter:
      - write-yaml
    taskRef:
      name: rox-deployment-check
      kind: ClusterTask
    workspaces:
      - name: deployfiles
        workspace: files
    params:
    - name: file
      value: "deploy.yml"
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
  - name: generate-netpol
    runAfter:
      - write-yaml
    taskRef:
      name: rox-generate-netpol
      kind: ClusterTask
    workspaces:
      - name: deployfiles
        workspace: files
    params:
    - name: file
      value: "deploy.yml"
    - name: rox_api_token
      value: roxsecrets
    - name: rox_central_endpoint
      value: roxsecrets
